from pyray import *
from raylib import *
from random import randint, choice
from os.path import join

WINDOW_WIDTH, WINDOW_HEIGHT = 1600,900
BG_COLOR = (15,10,25,255)
PLAYER_SPEED = 500
LASER_SPEED = 600
LASER_TIMER_COOLDOWN = 0.5
METEOR_SPEED_RANGE = [300,400]
METEOR_TIMER_DURATION = 0.4
# World Settings
CHUNK_SIZE = 1000
RENDER_DISTANCE = 3
STARS_PER_CHUNK = 50
MAX_STAR_RADIUS = 2
MOVEMENT_SPEED = 5
WORLD_THRESHOLD = 10_000
TEXT_LOCATION = Vector2(WINDOW_WIDTH/2,0)
TEXT_FONT_SIZE = 40
TEXT_SPACING = 5
TEXT_COLOR = WHITE
