from pyray import *
from raylib import *
from random import randint, choice
from os.path import join

WINDOW_WIDTH, WINDOW_HEIGHT = 1600,900
BG_COLOR = (15,10,25,255)
PLAYER_SPEED = 500
LASER_SPEED = 600
LASER_TIMER_COOLDOWN = 0.5
METEOR_SPEED_RANGE = [300,400]
METEOR_TIMER_DURATION = 0.4
# World Settings
CHUNK_SIZE = 1000
RENDER_DISTANCE = 3
STARS_PER_CHUNK = 50
MAX_STAR_RADIUS = 2
MOVEMENT_SPEED = 5
WORLD_THRESHOLD = 10_000

# Text Settings
#Score Settings
SCORE_LOCATION = Vector2(WINDOW_WIDTH/2,0)
SCORE_FONT_SIZE = 40
SCORE_SPACING = 5
SCORE_COLOR = WHITE

# Level Settings
LEVEL_TEXT_MESSAGE = "LEVEL COMPLETE!"
LEVEL_TEXT_SIZE = 50
LEVEL_TEXT_WIDTH = measure_text(LEVEL_TEXT_MESSAGE, LEVEL_TEXT_SIZE)
LEVEL_CONTINUE_MESSAGE = "Press 'Enter' to continue to the next level"
LEVEL_CONTINUE_TEXT_SIZE = 20
LEVEL_CONTINUE_TEXT_WIDTH = measure_text(LEVEL_CONTINUE_MESSAGE, 
                                         LEVEL_CONTINUE_TEXT_SIZE)
LEVEL_TEXT_LOCATION = Vector2((WINDOW_WIDTH - LEVEL_TEXT_WIDTH) / 2, 
                             (WINDOW_HEIGHT - LEVEL_TEXT_SIZE) / 2)
LEVEL_CONTINUE_TEXT_LOCATION = Vector2((WINDOW_WIDTH - LEVEL_CONTINUE_TEXT_WIDTH) / 2, 
                                       (WINDOW_HEIGHT + LEVEL_TEXT_SIZE) / 2 + 20)
LEVEL_TEXT_COLOR = GOLD
LEVEL_CONTINUE_TEXT_COLOR = RAYWHITE

# Game Over Settings
GAME_OVER_TEXT_MESSAGE = "GAME OVER!"
GAME_OVER_TEXT_SIZE = 60
GAME_OVER_TEXT_WIDTH = measure_text(GAME_OVER_TEXT_MESSAGE, GAME_OVER_TEXT_SIZE)
GAME_OVER_TEXT_LOCATION = Vector2((WINDOW_WIDTH - GAME_OVER_TEXT_WIDTH) / 2, 
                                   (WINDOW_HEIGHT - GAME_OVER_TEXT_SIZE) / 2)
GAME_OVER_TEXT_COLOR = RED
